[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[AbstractPlotting]]
deps = ["ColorBrewer", "ColorTypes", "Colors", "FreeType", "FreeTypeAbstraction", "GeometryTypes", "InteractiveUtils", "IntervalSets", "LinearAlgebra", "Markdown", "Observables", "Packing", "PlotUtils", "Printf", "Random", "Serialization", "Showoff", "SignedDistanceFields", "StaticArrays", "Statistics", "Test", "UnicodeFun"]
git-tree-sha1 = "c3bf268970d354b3c135153a522a084b5227dbf1"
repo-rev = "master"
repo-url = "https://github.com/JuliaPlots/AbstractPlotting.jl.git"
uuid = "537997a7-5e4e-5d89-9595-2241ea00577e"
version = "0.9.0+"

[[ArnoldiMethod]]
deps = ["DelimitedFiles", "LinearAlgebra", "Random", "SparseArrays", "StaticArrays", "Test"]
git-tree-sha1 = "2b6845cea546604fb4dca4e31414a6a59d39ddcd"
uuid = "ec485272-7323-5ecc-a04f-4719b315124d"
version = "0.0.4"

[[Arpack]]
deps = ["BinaryProvider", "Libdl", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "1ce1ce9984683f0b6a587d5bdbc688ecb480096f"
uuid = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
version = "0.3.0"

[[AxisAlgorithms]]
deps = ["Compat", "WoodburyMatrices"]
git-tree-sha1 = "99dabbe853e4f641ab21a676131f2cf9fb29937e"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.3.0"

[[AxisArrays]]
deps = ["Compat", "Dates", "IntervalSets", "IterTools", "Random", "RangeArrays", "Test"]
git-tree-sha1 = "2e2536e9e6f27c4f8d09d8442b61a7ae0b910c28"
uuid = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
version = "0.3.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "9930c1a6cd49d9fcd7218df6be417e6ae4f1468a"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.2"

[[CMake]]
deps = ["BinDeps", "Libdl", "Test"]
git-tree-sha1 = "74853a75c26a4a73ac391ee26ee29ebeb5583d9f"
uuid = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
version = "1.1.0"

[[CMakeWrapper]]
deps = ["BinDeps", "CMake", "Libdl", "Parameters", "Test"]
git-tree-sha1 = "2b43d451639984e3571951cc687b8509b0a86c6d"
uuid = "d5fb7624-851a-54ee-a528-d3f3bac0b4a0"
version = "0.2.2"

[[ColorBrewer]]
deps = ["Colors", "JSON", "Test"]
git-tree-sha1 = "61c5334f33d91e570e1d0c3eb5465835242582c4"
uuid = "a2cac450-b92f-5266-8821-25eda20663c8"
version = "0.4.0"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "f73b0e10f2a5756de7019818a41654686da06b09"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.5"

[[ColorVectorSpace]]
deps = ["ColorTypes", "Colors", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "StatsBase", "Test"]
git-tree-sha1 = "a890f08e61b40e9843d7177206da61229a3603c8"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.6.2"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "9f0a0210450acb91c730b730a994f8eef1d3d543"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.5"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "2d9e14d19bad3f9ad5cc5e4cffabc3cfa59de825"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.3.0"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "fb86fe40cb5b35990e368709bfdc1b46dbb99dac"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.1.1"

[[Contour]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "b974e164358fea753ef853ce7bad97afec15bb80"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.1"

[[CoordinateTransformations]]
deps = ["Compat", "Rotations", "StaticArrays"]
git-tree-sha1 = "47f05d0b7f4999609f92e657147df000818c1f24"
uuid = "150eb455-5306-5404-9cee-2592286d6298"
version = "0.5.0"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections", "Random", "Serialization", "Test"]
git-tree-sha1 = "8fc6e166e24fda04b2b648d4260cdad241788c54"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.14.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distances]]
deps = ["LinearAlgebra", "Printf", "Random", "Statistics", "Test"]
git-tree-sha1 = "2f38605722542f1c0a32dd2856fb529d8c226c69"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.7.3"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Reexport", "Test"]
git-tree-sha1 = "29cda58afbf62f35b1a094882ad6c745a47b2eaa"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.4"

[[FileIO]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "481e4db939f005db39f7296599d0543c0744fe30"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.0.2"

[[FixedPointNumbers]]
deps = ["Test"]
git-tree-sha1 = "b8045033701c3b10bf2324d7203404be7aef88ba"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.3"

[[FreeType]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Test"]
git-tree-sha1 = "06462b9d5aca708d764d16e5ba6a83ba7b753d57"
uuid = "b38be410-82b0-50bf-ab77-7b57e271db43"
version = "2.1.1"

[[FreeTypeAbstraction]]
deps = ["ColorVectorSpace", "Colors", "FreeType", "StaticArrays", "Test"]
git-tree-sha1 = "271ef13438bd0946950fd34d9241e5beefd6d4b3"
uuid = "663a7486-cb36-511b-a19d-713bb74d65c9"
version = "0.4.1"

[[GLFW]]
deps = ["BinDeps", "CMakeWrapper", "Homebrew", "Libdl", "Test"]
git-tree-sha1 = "5811de29ec3b96ab50e7043f0f0d688e085d1c07"
uuid = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
version = "2.2.0"

[[GeometryTypes]]
deps = ["ColorTypes", "FixedPointNumbers", "IterTools", "LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "765f6d4039ba2dd37b2936235012502aafbe8bfb"
uuid = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
version = "0.6.2"

[[Graphics]]
deps = ["Colors", "Compat", "NaNMath"]
git-tree-sha1 = "e3ead4211073d4117a0d2ef7d1efc5c8092c8412"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "0.4.0"

[[Homebrew]]
deps = ["BinDeps", "InteractiveUtils", "JSON", "Libdl", "Test", "Unicode"]
git-tree-sha1 = "5582ec74f735cf8d12e562a2e65c47f34063bd51"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.7.0"

[[IdentityRanges]]
deps = ["OffsetArrays", "Test"]
git-tree-sha1 = "f5ca23a08397288924a7535cd898d8ccbcde5ba5"
uuid = "bbac6d45-d8f3-5730-bfe4-7a449cd117ca"
version = "0.2.0"

[[ImageAxes]]
deps = ["AxisArrays", "Colors", "FixedPointNumbers", "ImageCore", "MappedArrays", "Reexport", "SimpleTraits", "Test"]
git-tree-sha1 = "5735ec90843acaa67a4624611921c686cdf4efbf"
uuid = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
version = "0.5.0"

[[ImageCore]]
deps = ["ColorTypes", "Colors", "FFTW", "FixedPointNumbers", "Graphics", "MappedArrays", "OffsetArrays", "PaddedViews", "Random", "Statistics", "Test"]
git-tree-sha1 = "5e7b1f49c80541860e08a7ea91805a24c1641f19"
uuid = "a09fc81d-aa75-5fe9-8630-4744c3626534"
version = "0.7.3"

[[ImageMagick]]
deps = ["BinaryProvider", "ColorTypes", "FileIO", "FixedPointNumbers", "ImageCore", "InteractiveUtils", "Libdl", "Pkg", "Random", "Test"]
git-tree-sha1 = "0e4cc77fb131061b3525a97fd7d483b253c3aaad"
uuid = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
version = "0.7.1"

[[ImageTransformations]]
deps = ["AxisAlgorithms", "ColorTypes", "ColorVectorSpace", "Colors", "CoordinateTransformations", "FixedPointNumbers", "IdentityRanges", "ImageCore", "Interpolations", "LinearAlgebra", "OffsetArrays", "StaticArrays", "Test"]
git-tree-sha1 = "904bcf19c10176fc0725d9fd94c79bcddb392e93"
uuid = "02fcd773-0e25-5acc-982a-7f6622650795"
version = "0.6.0"

[[IndirectArrays]]
deps = ["Compat", "Test"]
git-tree-sha1 = "b6e249be10a3381b2c72ac82f2d13d70067cb2bd"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "0.5.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "LinearAlgebra", "OffsetArrays", "Random", "Ratios", "SharedArrays", "SparseArrays", "StaticArrays", "Test", "WoodburyMatrices"]
git-tree-sha1 = "56691033f157dd1ee1d2aa042114caeefefa897b"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.10.5"

[[IntervalSets]]
deps = ["Compat"]
git-tree-sha1 = "9dc556002f23740de13946e8c2e41798e09a9249"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.3.1"

[[IterTools]]
deps = ["SparseArrays", "Test"]
git-tree-sha1 = "79246285c43602384e6f1943b3554042a3712056"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.1.1"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "fec8e4d433072731466d37ed0061b3ba7f70eeb9"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.19.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[LinearMaps]]
deps = ["LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "580bb0efbfe0082c4fb0ce8dbf6548872c3b604c"
uuid = "7a12625a-238d-50fd-b39a-03d52299707e"
version = "2.2.2"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "c443e1c8d58a4e9f61b708ad0a88286c7042145b"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.4"

[[Makie]]
deps = ["AbstractPlotting", "AxisArrays", "Base64", "ColorBrewer", "ColorTypes", "ColorVectorSpace", "Colors", "Contour", "Dates", "FileIO", "FixedPointNumbers", "FreeType", "FreeTypeAbstraction", "GLFW", "GeometryTypes", "ImageAxes", "ImageCore", "ImageMagick", "ImageTransformations", "IndirectArrays", "IntervalSets", "IterTools", "LinearAlgebra", "Markdown", "ModernGL", "Observables", "Pkg", "PlotUtils", "Primes", "Printf", "QuartzImageIO", "Random", "Serialization", "Showoff", "StaticArrays", "Statistics", "Test", "UnicodeFun"]
git-tree-sha1 = "4bd4f51f17348587e5063f37ef6b410c190a476e"
repo-rev = "master"
repo-url = "https://github.com/JuliaPlots/Makie.jl.git"
uuid = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
version = "0.9.0+"

[[MappedArrays]]
deps = ["Test"]
git-tree-sha1 = "923441c5ac942b60bd3a842d5377d96646bcbf46"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.2.1"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Missings]]
deps = ["Dates", "InteractiveUtils", "SparseArrays", "Test"]
git-tree-sha1 = "adc26d2ee85a49c413464110d922cf21efc9d233"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.3.1"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[ModernGL]]
deps = ["Libdl"]
git-tree-sha1 = "f4f8fa8d04d3c1e7294f07fc37586c819466ad38"
uuid = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
version = "1.0.0"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[NearestNeighbors]]
deps = ["Distances", "LinearAlgebra", "Mmap", "StaticArrays", "Test"]
git-tree-sha1 = "aab46b96ae5c2a9c08146188016d6312276094e5"
uuid = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
version = "0.4.2"

[[Observables]]
deps = ["Test"]
git-tree-sha1 = "752ef9b9ff1a7a6d764aee6be60cf0a5be7a21b1"
uuid = "510215fc-4207-5dde-b226-833fc4488ee2"
version = "0.2.2"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "f8cd140824f74f2948ff8660bc2292e16d29c1b7"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.1"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "85619a3f3e17bb4761fe1b1fd47f0e979f964d5b"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.0.2"

[[Packing]]
deps = ["GeometryTypes", "Test"]
git-tree-sha1 = "bc7c284233cf0518933bf9977e3e8234efcc1c30"
uuid = "19eb6ba3-879d-56ad-ad62-d5c202156566"
version = "0.3.0"

[[PaddedViews]]
deps = ["OffsetArrays", "Test"]
git-tree-sha1 = "7da3e7e1a58cffbf10177553ae95f17b92516912"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.4.2"

[[Parameters]]
deps = ["Markdown", "OrderedCollections", "REPL", "Test"]
git-tree-sha1 = "40f540ec96e50c0b2b9efdb11b5e4d0c63f90923"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.10.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotUtils]]
deps = ["Colors", "Dates", "Printf", "Random", "Reexport", "Test"]
git-tree-sha1 = "fd28f30a294a38ec847de95d8ac7ac916ccd7c06"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "0.5.5"

[[Primes]]
deps = ["Test"]
git-tree-sha1 = "ff1a2323cb468ec5f201838fcbe3c232266b1f95"
uuid = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
version = "0.4.0"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuartzImageIO]]
deps = ["ColorTypes", "ColorVectorSpace", "FileIO", "FixedPointNumbers", "ImageCore", "Libdl", "Random", "Test"]
git-tree-sha1 = "c747a56f223919b157e6cd9dc58d59c560586302"
uuid = "dca85d43-d64c-5e67-8c65-017450d5d020"
version = "0.5.0"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RangeArrays]]
deps = ["Compat"]
git-tree-sha1 = "d925adfd5b01cb46fde89dc9548d167b3b136f4a"
uuid = "b3c3ace0-ae52-54e7-9d0b-2c1406fd6b9d"
version = "0.3.1"

[[Ratios]]
deps = ["Compat"]
git-tree-sha1 = "fd159bead0a24e6270fd0573a340312bd4645cc2"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.3.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Rotations]]
deps = ["LinearAlgebra", "Random", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "b629771d0de88979cbdbf72ceddc54de58fde149"
uuid = "6038ab10-8711-5258-84ad-4b1120ba62dc"
version = "0.9.1"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Showoff]]
deps = ["Compat"]
git-tree-sha1 = "276b24f3ace98bec911be7ff2928d497dc759085"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.1"

[[SignedDistanceFields]]
deps = ["Random", "Statistics", "Test"]
git-tree-sha1 = "d263a08ec505853a5ff1c1ebde2070419e3f28e9"
uuid = "73760f76-fbc4-59ce-8f25-708e95d2df96"
version = "0.4.0"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools", "Test"]
git-tree-sha1 = "c0a542b8d5e369b179ccd296b2ca987f6da5da0a"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.8.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Libdl", "Test"]
git-tree-sha1 = "0b45dc2e45ed77f445617b99ff2adf0f5b0f23ea"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.2"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "ebc5c2a27d91d5ec611a9861168182e2168effd3"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.9.2"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "723193a13e8078cec6dcd0b8fe245c8bfd81690e"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.25.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[UnicodeFun]]
deps = ["Test"]
git-tree-sha1 = "63cbbd00217fc9aafedf055b60459c1ae7e01ecc"
uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1"
version = "0.4.0"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "c9d5aa108588b978bd859554660c8a5c4f2f7669"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.3"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "21772c33b447757ec7d3e61fcdfb9ea5c47eedcf"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.4.1"
